# Generated by Django 4.2 on 2026-05-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='RealEdge Africa Venture ltd', max_length=100)),
                ('description', models.TextField(default="RealEdge Africa Ventures is a global travel destinations' agent in Kenya specializing in Beach, Mountain Hiking adventures, Health & wellness, wildlife safari and Cultural experiences. We package your travel to fit your budget retaining great experience.")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('ssl_secured', models.BooleanField(default=True)),
                ('verified_business', models.BooleanField(default=True)),
                ('secure_payment', models.BooleanField(default=True)),
                ('till_number', models.CharField(blank=True, max_length=20)),
                ('till_name', models.CharField(blank=True, max_length=100)),
                ('paypal_enabled', models.BooleanField(default=True)),
                ('card_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
