# Generated by Django 4.2 on 2026-05-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
