# Generated by Django 4.2 on 2026-05-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_companysettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='paypal_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='primary_color',
            field=models.CharField(default='#9370ff', max_length=7),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='secondary_color',
            field=models.CharField(default='#7d4fff', max_length=7),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='support_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='254798400295', max_length=20),
        ),
    ]
